#include"a.h" // ngn/k, (c) 2019-2024 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/raw/branch/master/LICENSE
Z A1(sam,x)V_;T_;U _K(A x/*0*/)_(X(R2(tu,tw,1)Rv(2)Rx(x>>48&15)Ropqr(xk)RA(rnk(x)))0)
X1(mkn,RmMA(e1f(mkn,x))Rt(x(_R(cn[xt])))R_(P(!xn,x(_R(ce[xt])))x(rsz(xN,_R(cn[xt])))))
Z A1(iei,/*0*/0x2332211004>>(xv*(xtv&&xv<10u)<<2)&15)
Z Y2(iex,/*01*/RmMA(r2f(iex,x,y))RT_A(rsz(yN,iex(x,fir(y))))Rs(as(0))Rc(ac("\0\1\x7f\x80 "[iei(x)]))Rf(y(af(A(0.,1.,WF,-WF,NF)[iei(x)])))R_(y(az(G(0ll,1,WL,-WL,NL)[iei(x)]))))
A2(ie,/*00*/x==CAT?emp(yt):iex(x,fir(yR)))
AX(prj,XmMA(x8(a,n))U k=MAX(n,xK);F(n,k-=a[i]!=GAP)x=(xtp?val:aA1)(xR);I i=0,j=1;W(i<n&&j<xn,I(xA[j]==GAP,xA[j]=a[i++])j++)W(i<n,PSH(x,a[i++]))P(xn>9,ez(x))AT(tp,AK(k,x)))
A2(com,/*01*/AK(yK,AT(tq,aA2(y,xR))))
Z A iM(A x,L i)_(Q(xtM);A y=xy,z=aA(yn);Q(ytA);Fj(zn|!zn,zA[j]=io(yA[j],i))am(_R(xx),sqz(z)))
A ii(A x/*0*/,U i)_(X(RA(_R(xa))RC(ac(xc))RG(ai(xg))RH(ai(xh))RI(ai(xi))RL(al(xl))RF(af(xf))RS(as(xi))Rm(ii(xy,i))RM(iM(x,i))RE(az(*xL+i))RB(ai(xG[i>>3]>>(i&7)&1))R_(xR))0)
A io(A x/*0*/,L i)_(X(RE(i<(W)(xL[1]-*xL)?az(*xL+i):_R(cn[tl]))RT_E(i<(W)xn?ii(x,i):xn?mkn(ii(x,0)):xtA?_R(xx):_R(cn[xt]))Rt(xR)Rm(io(xy,i))RM(iM(x,i)))0)
A1(fir,x(io(x,0)))A1(las,x(io(x,xN-1)))

ZN U maxfU(CO V*x,U n,U w)_(U u=0;S4(w,F(n,u=MAX(u,xg)),F(n,u=MAX(u,xh)),F(n,u=MAX(u,xi)),)u)
#define ambcn CO V*RES a,U m,CO V*RES b,V*RES c,U n
#define M(tx,ty) Z V i##tx##ty(ambcn){CO tx*p=a;CO ty*q=b;tx*r=c;F(n,*r++=p[*q++])}
M(G,G)M(G,H)M(G,I)M(H,G)M(H,H)M(H,I)M(I,G)M(I,H)M(I,I)M(L,G)M(L,H)M(L,I)
#undef M
#define M(tx,ty) Z V o##tx##ty(ambcn,L v){CO tx*p=a;CO ty*q=b;L*r=c;F(n,*r++=q[i]<m?p[q[i]]:v)}
M(G,G)M(G,H)M(G,I)M(H,G)M(H,H)M(H,I)M(I,G)M(I,H)M(I,I)M(L,G)M(L,H)M(L,I)
#undef M
#define M(tx,ty,s) Z V o##tx##ty(ambcn){CO tx*p=a;CO ty*q=b;tx*r=c;F(n,*r++=q[i]<m?p[q[i]]:s)}
M(C,G,32)M(C,H,32)M(C,I,32)M(U,G,0)M(U,H,0)M(U,I,0)
#undef M
#undef ambcn

A2(i1,/*01*/P(y==GAP||y==au,xR)
 X(Rt(y(xR))
   RE(x=gZ(xR);x(i1(x,y)))
   RB(x=cG(xR);x(i1(x,y)))
   Rm(i1(xy,N(fnd(xx,y))))
   RM(Y(RsS(x=flp(xR);x(i1(x,y)))RA(r2(AP1,x,y))RmM(C t=yt;A z=kv(&y);A u=am(y,Ny(i1(x,z)));t==tM?flp(u):u)R_(B d=ytmt;y=N(l2f(i1,xy,y));(d?am:aM)(_R(xx),y)))0)
   R_(Y(Rilc(io(x,gl(y)))
        RmM(C t=yt;A z=kv(&y);A u=am(y,Ny(i1(x,z)));P(t==tM,flp(u))u)
        RA(r2(AP1,x,y))
        RE(L i=*yL,j=yL[1];P(0<=i&&i<j&&j<xN,y(0);slc(x,i,j))i1(x,gZ(y)))
        RB(i1(x,cI(y)))
        R_(et(y))
        RL(U m=xn;A z=aI(yn);F(yn+3&-4,L v=yl;zi=v|-(v!=(I)v))y(i1(x,z)))
        R4(tG,tH,tI,tC,C t=xt;U n=yn,m=xn,wx=xw-3,wy=yw-3,wxy=wx<<2|wy;A u=0;
         B o=m<=maxfU(yV,n,wy);A z=an(MAX(n,t==tA),o&&LH(tG,t,tL)?tL:t);
         I(!o,   G(&iGG,iGH,iGI,0,iHG,iHH,iHI,0,iIG,iIH,iII,0,iLG,iLH,iLI,0)[wxy](xV,m,yV,zV,n))
         J(t<=tF,G(&oGG,oGH,oGI,0,oHG,oHH,oHI,0,oIG,oIH,oII,0,oLG,oLH,oLI,0)[wxy](xV,m,yV,zV,n,t==tF?NFL:t==tA?(u=mkn(_R(xx))):NL))
         E(      G(&oCG,oCH,oCI,0,0  ,0  ,0  ,0,oUG,oUH,oUI,0,0  ,0  ,  0,0)[wxy](xV,m,yV,zV,n))
         I(t==tA,I(!n,zx=mkn(_R(xx));zn=0)mRn(n,zV);z=sqz(z);I(u,u(0)))
         y(z)))0))0)
Z A3(i2,/*011*/C b=ytT||y==GAP||y==au;x=Nz(i1(x,y));P(!b,x(x1(z)))x(l2f(dot,x,aA1(z))))
Z AX(i8,A y=*a;a++;n--;C b=ytT||y==GAP||y==au;x=i1(x,y);P(!x,mrn(n,a);x)P(!b,x(x8(a,n)))x(l2f(dot,x,aV(tA,n,a))))
L iw(A x/*0*/,U w,L i)_(S4(w,_(xg),_(xh),_(xi),_(xl))0)
Z A1(qa,A y=emp(tA);S*p=argv;W(*p,PSH(y,aCz(*p++)))y(y1(x)))
Z A1(qe,A y=emp(tS),z=emp(tA);S*e=env;W(*e,S p=*e++,q=strchrnul(p,'=');PSH(y,cS(aCm(p,q)));PSH(z,aCz(q+!!*q)))y=am(y,z);x-au?x(x1(y)):y)
Z A1(qx,exit(xtz?gl(x):1);0)
Z X1(qjs,RC(C b[4096];U n=js_eval(xC,xn,b,SZ b);x(0);aCn(b,n))RA(e1f(qjs,x))R_(et(x)))
Z X1(qp,RC(x=str0(x);S s=xC;x(pk(&s,0)))R_(et(x)))
Z A1(qt,x(al(now())))
Z A2(qo_,XSA(P(!xn,y)PSH(y,al(xo));XA(F(xn,y=qo_(xa,y));y)y)y)
Z A1(qo,A y=an(0,tI);x(qo_(x,y)))
Z A1(qfb,P(!xtC,et(x))P(xn-8,el(x))x=rev(x);x(aV(tf,1,xV)))//float from bits
ZN AX(ext,P(n-xK,er8(a,n))V*f=(V*)(x&-1ull>>16);S(n,R(1,((A1*)f)(a[0]))R(2,((A2*)f)(a[0],a[1]))R(3,((A3*)f)(a[0],a[1],a[2]))R(4,((A4*)f)(a[0],a[1],a[2],a[3]))R(5,((A5*)f)(a[0],a[1],a[2],a[3],a[4]))R(6,((A6*)f)(a[0],a[1],a[2],a[3],a[4],a[5]))R(7,((A7*)f)(a[0],a[1],a[2],a[3],a[4],a[5],a[6]))R(8,((A8*)f)(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7]))R_(en8(a,n)))0)
ZN A sym1(I v,A x)_(Z CO C s[][4]={"","k","j","o","p","t","x","hex","err","argv","env","exit","js","pri","prng","sin","cos","exp","ln","fb"};
 G(&ser,kst,js1,qo,qp,qt,frk,hex,err,qa,qe,qx,qjs,qpri,prng,ksin,kcos,kexp,klog,qfb,ed)[fI((V*)s,L(s),v)](x))
A2(_1,/*01*/P(!xtt,i1(x,y))U k=xK;P(1<k,k==2&&!xtp?prj(x,A8(y,GAP),2):prj(x,&y,1))
 X(Ro(run(x,&y,1))Rp(P(k>7,er(y))I m=xn-1,j=0;Ab8;F(m,b[i]=xA[i+1]==GAP&&!j?j++,y:_R(xA[i+1]))I l=MAX(0,1-j);MC(b+m,&y,l*SZ(A));_8(xx,b,m+l))
  Rq(F(xn,y=N(_1(xa,y)))y)Rr(w1(xE,xx,y))Rs(sym1(xv,y))Ru(v1[xv](y))Rw(AK(xv-1<3u&&yK==2?1:ytU?yK:1,ar(y,xv)))Rx(ext(x,&y,1))R_(et(y)))0)
A2(ed2,x(ed(y)))ZN A sym2(I v,A x,A y)_(Z CO C s[][4]={""};G(&ser2,ed2)[fI((V*)s,L(s),v)](x,y))
A3(_2,/*011*/P(!xtt,i2(x,y,z))A a[]={y,z};U k=xK;P(2<k,prj(x,a,2))
 X(Ro(run(x,a,2))Rp(P(k>6,er(z))I m=xn-1,j=0;Ab8;F(m,b[i]=xA[i+1]==GAP&&j<2?a[j++]:_R(xA[i+1]))I l=MAX(0,2-j);MC(b+m,a+j,l*SZ(A));_8(xx,b,m+l))
   Rq(_1(xy,N(_2(xx,y,z))))Rr(w2(xE,xx,y,z))Rv(y(v2[xv](y,z)))Rw(P(!xv,y(com(y,z)))x=Nz(x1(y));x(x1(z)))Rx(ext(x,A8(y,z),2))Rs(sym2(xv,y,z))R_(et(y(z))))0)
AX(_8,/*01..1*/Q(n)P(n==1,x1(*a))P(n==2&&!xtp,A y=*a;x2(y,a[1]))P(!xtt,i8(x,a,n))U k=xK;P(n<k,prj(x,a,n))
 X(Ro(run(x,a,n))Rp(P(xn-k+1+n>8,er8(a,n))I m=xn-1,j=0;Ab8;F(m,b[i]=xA[i+1]==GAP&&j<n?a[j++]:_R(xA[i+1]))I l=MAX(0,n-j);P(l+m>8,mrn(m,b);er8(a,n))MC(b+m,a+j,l*SZ(A));_8(xx,b,m+l))
   Rq(_1(xy,N(_8(xx,a,n))))Rr(w8(xE,xx,a,n))Rv(x=v8[xv](a,n);mrn(n-1,a+1);x)Rx(ext(x,a,n))R_(et8(a,n)))0)
A1(jS,cS(jc('.',str(x))))//join symbols with "."
X1(val,RA(P(!xn,x)P(xn==1,fir(x))P(xn>9,ez(x))x=mut(x);A y=_8(xx,&xy,xn-1);AN(1,x);x(y))RmM(x(_R(xy)))RE(gZ(x))RC(x=str0(x);x(evs(xV,0)))Rc(val(enl(x)))RsS(gg(x))
 Ropq(A y=AT(tA,mut(x));xtq?rev(y):y)Rr(cat10(AT(tA,mut(x)),aw+xE))Ruvw(ai(xv))R_(x))
A2(dot,/*01*/Ym(et(y))U n=yN;P(!n,y(xR))P(n>8,ez(y))y=mRa(N(blw(y)));y(x8(yA,n)))
Z U knd(A x/*0*/)_(X(Ril(ti)REBGHIL(tI)R_(xt))0)
Z A set(A x,L i,A y/*1i1*/)_(Q(MINE(x));
 X(RA(A z=xa;xa=z(y);ytt&&!ytU?sqz(x):x)
   RM(A z=kv(&x);z=mut(z);Q(ztA);I(ytT&&yN-zn,x(y(el(z))))I j=i;F(zn,za=set(mut(za),j,ii(y,i));P(!za,za=au;x(y(z(0)))))y(aM(x,z)))
   RB(P(yv<2u,xL[i>>6]&=~(1llu<<(i&~(-1llu<<6)));xL[i>>6]|=((W)yv)<<(i&~(-1llu<<6));x)set(cG(x),i,y))
   R_(P(knd(x)-knd(y)-tC+tc,set(blw(x),i,y))I(xtZ,N(sup(&x,&y)))C w=xw-3;!w?xg=yv:w==1?xh=yv:w==2?xi=yv:(xl=gl(y));x))0)
AA(a8,/*10..0*/A x=*a,y=a[1];
 X(RE(Ab8;*b=gZ(x);MC(b+1,a+1,(n-1)*SZ(A));a8(b,n))
   RT_E(P(y==au,mRn(n-2,a+2);Ab8;*b=a[2];b[1]=x;MC(b+2,a+3,(n-3)*SZ(A));e8(AP1,b,n-1))
    Yzc(L i=gl_(y);P(i>=(W)xn,ei(x))x=mut(x);Ab8;MC(b+1,a+3,(n-3)*SZ(A));mRn(n-3,b+1);A z=a[2];P(xtA&&MINE(x)&&!_tP(xa)&&MINE(xa),*b=xa;xa=N(z8(b,n-2),xa=au;mr(x));sqz(x))*b=ii(x,i);set(x,i,Nx(z8(b,n-2))))
    I(ytZC&&n==4,A z=a[2],u=a[3];P(xtZ&&ztv&&utzZ&&(0xcf&1<<zv),ara(x,y,z,u))P(xtC&&z==av&&utcC,cC(N(ara(x,y,z,u)))))Yt(et(x))mRn(n-1,a+1);f8(AP1,a,n))
   Rm(A z=Nx(fnd(xx,yR));ZT(z(0);mRn(n-1,a+1);f8(AP1,a,n))x=mut(x);I(ztl,z=mut(z);F(zN,I(zl==NL,zl=xN;PSH(xx,ztt?yR:ii(y,i));PSH(xy,ie(a[2],xy)))))
    Ab8;*b=xy;b[1]=z;MC(b+2,a+2,(n-2)*SZ(A));xy=au;xy=Nx(z(a8(b,n)));x)
   RM(Ab8;MC(b,a,n*SZ(A));YsS(*b=flp(x);flp(N(a8(b,n))))*b=blw(x);sqz(N(a8(b,n))))
   RU(mRn(n-1,a+1);x(x8(a+1,n-1)))
   R_(et(x)))0)
Z A3(a3,/*100*/a8(A8(x,y,z),3))
A4(a4,/*1000*/a8(A8(x,y,z,u),4))
Z A a5(A x,A y,A z,A u,A v/*10000*/)_(a8(A8(x,y,z,u,v),5))
Z A3(d3,/*100*/U m=yN;P(y==au||!m,z1(x))P(m==1,y=fir(yR);y(a3(x,y,z)))A u=prj(DOT,(A[]){GAP,drp(1,yR)},2);y=fir(yR);y(u(a4(x,y,u,z))))
A4(d4,/*1000*/U m=yN;P(y==au||!m,z2(x,uR))P(m==1,y=fir(yR);y(a4(x,y,z,u)))A v=prj(DOT,(A[]){GAP,drp(1,yR)},2);y=fir(yR);A r=y(a5(x,y,v,z,u));mr(v);r)
Z AA(d8_,/*10..0*/A x=*a,y=a[1],z=a[2];P(n==4,d4(x,y,z,a[3]))P(n==3,d3(x,y,z))en(x))
AA(d8,/*10..0*/A x=*a;
 X(RsS(A*p=gp(x);I(!*p,*p=au)Ab8;*b=*p;MC(b+1,a+1,(n-1)*SZ(A));*p=au;*p=_R(N(d8_(b,n))))
   RU(n==3?try(x,a[1],a[2]):er(x))
   R_(d8_(a,n)))0)
ZN A ki(A*p,S s)_(*p=ksg(s);I(!*p,die(s))PSH(cns,*p);*p)
A k1(A*p,S s,A x)_(I(!*p,ki(p,s))_1(*p,x))
A k2(A*p,S s,A x,A y)_(A z=*p;I(!z,z=ki(p,s))z2(xR,y))
A k8(A*p,S s,CO A*a,U n)_(I(!*p,ki(p,s))n?_8(*p,a,n):*p)
AA(no8,/*10..0*/en(*a))
