// ngn/k, (c) 2019-2020 ngn, license: GNU AGPLv3 - https://bitbucket.org/ngn/k/raw/master/LICENSE
// generated by g.k
#define xk Ak(x)
#define xn An(x)
#define xo Ao(x)
#define xt At(x)
#define xv Av(x)
#define yk Ak(y)
#define yn An(y)
#define yo Ao(y)
#define yt At(y)
#define yv Av(y)
#define zk Ak(z)
#define zn An(z)
#define zo Ao(z)
#define zt At(z)
#define zv Av(z)
#define uk Ak(u)
#define un An(u)
#define uo Ao(u)
#define ut At(u)
#define uv Av(u)
#define xr ({mr(x);dbg(x=0;)})
#define yr ({mr(y);dbg(y=0;)})
#define zr ({mr(z);dbg(z=0;)})
#define ur ({mr(u);dbg(u=0;)})
#define xR mR(x)
#define yR mR(y)
#define zR mR(z)
#define uR mR(u)
#define xa xA[i]
#define xc xC[i]
#define xh xH[i]
#define xi xI[i]
#define xl xL[i]
#define xd xD[i]
#define ya yA[i]
#define yc yC[i]
#define yh yH[i]
#define yi yI[i]
#define yl yL[i]
#define yd yD[i]
#define za zA[i]
#define zc zC[i]
#define zh zH[i]
#define zi zI[i]
#define zl zL[i]
#define zd zD[i]
#define ua uA[i]
#define uc uC[i]
#define uh uH[i]
#define ui uI[i]
#define ul uL[i]
#define ud uD[i]
#define xA ((A*)dat(x))
#define xC ((C*)dat(x))
#define xH ((H*)dat(x))
#define xI ((I*)dat(x))
#define xL ((L*)dat(x))
#define xD ((D*)dat(x))
#define yA ((A*)dat(y))
#define yC ((C*)dat(y))
#define yH ((H*)dat(y))
#define yI ((I*)dat(y))
#define yL ((L*)dat(y))
#define yD ((D*)dat(y))
#define zA ((A*)dat(z))
#define zC ((C*)dat(z))
#define zH ((H*)dat(z))
#define zI ((I*)dat(z))
#define zL ((L*)dat(z))
#define zD ((D*)dat(z))
#define uA ((A*)dat(u))
#define uC ((C*)dat(u))
#define uH ((H*)dat(u))
#define uI ((I*)dat(u))
#define uL ((L*)dat(u))
#define uD ((D*)dat(u))
#define xx xA[0]
#define xy xA[1]
#define xz xA[2]
#define yx yA[0]
#define yy yA[1]
#define yz yA[2]
#define zx zA[0]
#define zy zA[1]
#define zz zA[2]
#define ux uA[0]
#define uy uA[1]
#define uz uA[2]
#define xtA (xt==tA)
#define xtC (xt==tC)
#define xtH (xt==tH)
#define xtI (xt==tI)
#define xtL (xt==tL)
#define xtD (xt==tD)
#define xtS (xt==tS)
#define xtM (xt==tM)
#define xtm (xt==tm)
#define xtc (xt==tc)
#define xth (xt==th)
#define xti (xt==ti)
#define xtl (xt==tl)
#define xtd (xt==td)
#define xts (xt==ts)
#define xto (xt==to)
#define xtp (xt==tp)
#define xtq (xt==tq)
#define xtr (xt==tr)
#define xtu (xt==tu)
#define xtv (xt==tv)
#define xtw (xt==tw)
#define ytA (yt==tA)
#define ytC (yt==tC)
#define ytH (yt==tH)
#define ytI (yt==tI)
#define ytL (yt==tL)
#define ytD (yt==tD)
#define ytS (yt==tS)
#define ytM (yt==tM)
#define ytm (yt==tm)
#define ytc (yt==tc)
#define yth (yt==th)
#define yti (yt==ti)
#define ytl (yt==tl)
#define ytd (yt==td)
#define yts (yt==ts)
#define yto (yt==to)
#define ytp (yt==tp)
#define ytq (yt==tq)
#define ytr (yt==tr)
#define ytu (yt==tu)
#define ytv (yt==tv)
#define ytw (yt==tw)
#define ztA (zt==tA)
#define ztC (zt==tC)
#define ztH (zt==tH)
#define ztI (zt==tI)
#define ztL (zt==tL)
#define ztD (zt==tD)
#define ztS (zt==tS)
#define ztM (zt==tM)
#define ztm (zt==tm)
#define ztc (zt==tc)
#define zth (zt==th)
#define zti (zt==ti)
#define ztl (zt==tl)
#define ztd (zt==td)
#define zts (zt==ts)
#define zto (zt==to)
#define ztp (zt==tp)
#define ztq (zt==tq)
#define ztr (zt==tr)
#define ztu (zt==tu)
#define ztv (zt==tv)
#define ztw (zt==tw)
#define utA (ut==tA)
#define utC (ut==tC)
#define utH (ut==tH)
#define utI (ut==tI)
#define utL (ut==tL)
#define utD (ut==tD)
#define utS (ut==tS)
#define utM (ut==tM)
#define utm (ut==tm)
#define utc (ut==tc)
#define uth (ut==th)
#define uti (ut==ti)
#define utl (ut==tl)
#define utd (ut==td)
#define uts (ut==ts)
#define uto (ut==to)
#define utp (ut==tp)
#define utq (ut==tq)
#define utr (ut==tr)
#define utu (ut==tu)
#define utv (ut==tv)
#define utw (ut==tw)
#define xtcC (xtc||xtC)
#define xthH (xth||xtH)
#define xtiI (xti||xtI)
#define xtlL (xtl||xtL)
#define xtdD (xtd||xtD)
#define xtsS (xts||xtS)
#define xtmM (xtm||xtM)
#define xtilIL (xtil||xtIL)
#define ytcC (ytc||ytC)
#define ythH (yth||ytH)
#define ytiI (yti||ytI)
#define ytlL (ytl||ytL)
#define ytdD (ytd||ytD)
#define ytsS (yts||ytS)
#define ytmM (ytm||ytM)
#define ytilIL (ytil||ytIL)
#define ztcC (ztc||ztC)
#define zthH (zth||ztH)
#define ztiI (zti||ztI)
#define ztlL (ztl||ztL)
#define ztdD (ztd||ztD)
#define ztsS (zts||ztS)
#define ztmM (ztm||ztM)
#define ztilIL (ztil||ztIL)
#define utcC (utc||utC)
#define uthH (uth||utH)
#define utiI (uti||utI)
#define utlL (utl||utL)
#define utdD (utd||utD)
#define utsS (uts||utS)
#define utmM (utm||utM)
#define utilIL (util||utIL)
#define xtmMA (xtmM||xtA)
#define ytmMA (ytmM||ytA)
#define ztmMA (ztmM||ztA)
#define utmMA (utmM||utA)
#define xtil (xti||xtl)
#define ytil (yti||ytl)
#define ztil (zti||ztl)
#define util (uti||utl)
#define xtIL (xtI||xtL)
#define ytIL (ytI||ytL)
#define ztIL (ztI||ztL)
#define utIL (utI||utL)
#define xtt (xt>tm)
#define ytt (yt>tm)
#define ztt (zt>tm)
#define utt (ut>tm)
#define xtT (xt<tM)
#define ytT (yt<tM)
#define ztT (zt<tM)
#define utT (ut<tM)
#define XA(a...) P(xtA,a)
#define XC(a...) P(xtC,a)
#define XH(a...) P(xtH,a)
#define XI(a...) P(xtI,a)
#define XL(a...) P(xtL,a)
#define XD(a...) P(xtD,a)
#define XS(a...) P(xtS,a)
#define XM(a...) P(xtM,a)
#define Xm(a...) P(xtm,a)
#define Xc(a...) P(xtc,a)
#define Xh(a...) P(xth,a)
#define Xi(a...) P(xti,a)
#define Xl(a...) P(xtl,a)
#define Xd(a...) P(xtd,a)
#define Xs(a...) P(xts,a)
#define Xo(a...) P(xto,a)
#define Xp(a...) P(xtp,a)
#define Xq(a...) P(xtq,a)
#define Xr(a...) P(xtr,a)
#define Xu(a...) P(xtu,a)
#define Xv(a...) P(xtv,a)
#define Xw(a...) P(xtw,a)
#define XT(a...) P(xtT,a)
#define Xt(a...) P(xtt,a)
#define YA(a...) P(ytA,a)
#define YC(a...) P(ytC,a)
#define YH(a...) P(ytH,a)
#define YI(a...) P(ytI,a)
#define YL(a...) P(ytL,a)
#define YD(a...) P(ytD,a)
#define YS(a...) P(ytS,a)
#define YM(a...) P(ytM,a)
#define Ym(a...) P(ytm,a)
#define Yc(a...) P(ytc,a)
#define Yh(a...) P(yth,a)
#define Yi(a...) P(yti,a)
#define Yl(a...) P(ytl,a)
#define Yd(a...) P(ytd,a)
#define Ys(a...) P(yts,a)
#define Yo(a...) P(yto,a)
#define Yp(a...) P(ytp,a)
#define Yq(a...) P(ytq,a)
#define Yr(a...) P(ytr,a)
#define Yu(a...) P(ytu,a)
#define Yv(a...) P(ytv,a)
#define Yw(a...) P(ytw,a)
#define YT(a...) P(ytT,a)
#define Yt(a...) P(ytt,a)
#define Nx(r) N1(x,r)
#define Ny(r) N1(y,r)
#define Nz(r) N1(z,r)
#define Nu(r) N1(u,r)
#define Cb C b
#define Cc C c
#define Cd C d
#define Ck C k
#define Cn C n
#define Co C o
#define Ct C t
#define Cv C v
#define Hi H i
#define Hj H j
#define Hk H k
#define Hm H m
#define Hn H n
#define Hv H v
#define Ii I i
#define Ij I j
#define Ik I k
#define Im I m
#define In I n
#define Iv I v
#define Li L i
#define Lj L j
#define Lk L k
#define Lm L m
#define Ln L n
#define Lv L v
#define Dd D d
#define Dv D v
#define Ax A x
#define Ay A y
#define Az A z
#define Au A u
#define OA O A
#define OC O C
#define OV O V
#define Ec(a...) E_(c,a)
#define Ed(a...) E_(d,a)
#define Ei(a...) E_(i,a)
#define El(a...) E_(l,a)
#define En(a...) E_(n,a)
#define Eo(a...) E_(o,a)
#define Ep(a...) E_(p,a)
#define Er(a...) E_(r,a)
#define Es(a...) E_(s,a)
#define Et(a...) E_(t,a)
#define Ev(a...) E_(v,a)
#define Ez(a...) E_(z,a)
#define xq(a) (x=apd(x,(a)))
#define yq(a) (y=apd(y,(a)))
#define zq(a) (z=apd(z,(a)))
#define uq(a) (u=apd(u,(a)))
