// ngn/k, (c) 2019-2021 ngn, license: GNU AGPLv3 - https://codeberg.org/ngn/k/blob/master/LICENSE
// generated by g.k
#define xk    _k(x)
#define xn    _n(x)
#define xN    _N(x)
#define xo    _o(x)
#define xr    _r(x)
#define xt    _t(x)
#define xv    _v(x)
#define yk    _k(y)
#define yn    _n(y)
#define yN    _N(y)
#define yo    _o(y)
#define yr    _r(y)
#define yt    _t(y)
#define yv    _v(y)
#define zk    _k(z)
#define zn    _n(z)
#define zN    _N(z)
#define zo    _o(z)
#define zr    _r(z)
#define zt    _t(z)
#define zv    _v(z)
#define uk    _k(u)
#define un    _n(u)
#define uN    _N(u)
#define uo    _o(u)
#define ur    _r(u)
#define ut    _t(u)
#define uv    _v(u)
#define xR    mR(x)
#define yR    mR(y)
#define zR    mR(z)
#define uR    mR(u)
#define x(a)  dex(x,a)
#define y(a)  dex(y,a)
#define z(a)  dex(z,a)
#define u(a)  dex(u,a)
#define xA    ((A*)_V(x))
#define xC    ((C*)_V(x))
#define xB    ((B*)_V(x))
#define xH    ((H*)_V(x))
#define xI    ((I*)_V(x))
#define xL    ((L*)_V(x))
#define xD    ((D*)_V(x))
#define yA    ((A*)_V(y))
#define yC    ((C*)_V(y))
#define yB    ((B*)_V(y))
#define yH    ((H*)_V(y))
#define yI    ((I*)_V(y))
#define yL    ((L*)_V(y))
#define yD    ((D*)_V(y))
#define zA    ((A*)_V(z))
#define zC    ((C*)_V(z))
#define zB    ((B*)_V(z))
#define zH    ((H*)_V(z))
#define zI    ((I*)_V(z))
#define zL    ((L*)_V(z))
#define zD    ((D*)_V(z))
#define uA    ((A*)_V(u))
#define uC    ((C*)_V(u))
#define uB    ((B*)_V(u))
#define uH    ((H*)_V(u))
#define uI    ((I*)_V(u))
#define uL    ((L*)_V(u))
#define uD    ((D*)_V(u))
#define xa    xA[i]
#define xc    xC[i]
#define xb    xB[i]
#define xh    xH[i]
#define xi    xI[i]
#define xl    xL[i]
#define xd    xD[i]
#define ya    yA[i]
#define yc    yC[i]
#define yb    yB[i]
#define yh    yH[i]
#define yi    yI[i]
#define yl    yL[i]
#define yd    yD[i]
#define za    zA[i]
#define zc    zC[i]
#define zb    zB[i]
#define zh    zH[i]
#define zi    zI[i]
#define zl    zL[i]
#define zd    zD[i]
#define ua    uA[i]
#define uc    uC[i]
#define ub    uB[i]
#define uh    uH[i]
#define ui    uI[i]
#define ul    uL[i]
#define ud    uD[i]
#define xx    xA[0]
#define yx    yA[0]
#define zx    zA[0]
#define ux    uA[0]
#define xy    xA[1]
#define yy    yA[1]
#define zy    zA[1]
#define uy    uA[1]
#define xz    xA[2]
#define yz    yA[2]
#define zz    zA[2]
#define uz    uA[2]
#define xtA   (xt==tA)
#define xtC   (xt==tC)
#define xtB   (xt==tB)
#define xtH   (xt==tH)
#define xtI   (xt==tI)
#define xtL   (xt==tL)
#define xtD   (xt==tD)
#define xtS   (xt==tS)
#define xtM   (xt==tM)
#define xtm   (xt==tm)
#define xtc   (xt==tc)
#define xti   (xt==ti)
#define xtl   (xt==tl)
#define xtd   (xt==td)
#define xts   (xt==ts)
#define xto   (xt==to)
#define xtp   (xt==tp)
#define xtq   (xt==tq)
#define xtr   (xt==tr)
#define xtu   (xt==tu)
#define xtv   (xt==tv)
#define xtw   (xt==tw)
#define xte   (xt==te)
#define ytA   (yt==tA)
#define ytC   (yt==tC)
#define ytB   (yt==tB)
#define ytH   (yt==tH)
#define ytI   (yt==tI)
#define ytL   (yt==tL)
#define ytD   (yt==tD)
#define ytS   (yt==tS)
#define ytM   (yt==tM)
#define ytm   (yt==tm)
#define ytc   (yt==tc)
#define yti   (yt==ti)
#define ytl   (yt==tl)
#define ytd   (yt==td)
#define yts   (yt==ts)
#define yto   (yt==to)
#define ytp   (yt==tp)
#define ytq   (yt==tq)
#define ytr   (yt==tr)
#define ytu   (yt==tu)
#define ytv   (yt==tv)
#define ytw   (yt==tw)
#define yte   (yt==te)
#define ztA   (zt==tA)
#define ztC   (zt==tC)
#define ztB   (zt==tB)
#define ztH   (zt==tH)
#define ztI   (zt==tI)
#define ztL   (zt==tL)
#define ztD   (zt==tD)
#define ztS   (zt==tS)
#define ztM   (zt==tM)
#define ztm   (zt==tm)
#define ztc   (zt==tc)
#define zti   (zt==ti)
#define ztl   (zt==tl)
#define ztd   (zt==td)
#define zts   (zt==ts)
#define zto   (zt==to)
#define ztp   (zt==tp)
#define ztq   (zt==tq)
#define ztr   (zt==tr)
#define ztu   (zt==tu)
#define ztv   (zt==tv)
#define ztw   (zt==tw)
#define zte   (zt==te)
#define utA   (ut==tA)
#define utC   (ut==tC)
#define utB   (ut==tB)
#define utH   (ut==tH)
#define utI   (ut==tI)
#define utL   (ut==tL)
#define utD   (ut==tD)
#define utS   (ut==tS)
#define utM   (ut==tM)
#define utm   (ut==tm)
#define utc   (ut==tc)
#define uti   (ut==ti)
#define utl   (ut==tl)
#define utd   (ut==td)
#define uts   (ut==ts)
#define uto   (ut==to)
#define utp   (ut==tp)
#define utq   (ut==tq)
#define utr   (ut==tr)
#define utu   (ut==tu)
#define utv   (ut==tv)
#define utw   (ut==tw)
#define ute   (ut==te)
#define xtF   _tF(xt)
#define xtP   _tP(xt)
#define xtR   _tR(xt)
#define xtz   _tz(xt)
#define xtZ   _tZ(xt)
#define xtt   _tt(xt)
#define xtT   _tT(xt)
#define ytF   _tF(yt)
#define ytP   _tP(yt)
#define ytR   _tR(yt)
#define ytz   _tz(yt)
#define ytZ   _tZ(yt)
#define ytt   _tt(yt)
#define ytT   _tT(yt)
#define ztF   _tF(zt)
#define ztP   _tP(zt)
#define ztR   _tR(zt)
#define ztz   _tz(zt)
#define ztZ   _tZ(zt)
#define ztt   _tt(zt)
#define ztT   _tT(zt)
#define utF   _tF(ut)
#define utP   _tP(ut)
#define utR   _tR(ut)
#define utz   _tz(ut)
#define utZ   _tZ(ut)
#define utt   _tt(ut)
#define utT   _tT(ut)
#define xtcC  (xtc||xtC)
#define xtbB  (xtb||xtB)
#define xthH  (xth||xtH)
#define xtiI  (xti||xtI)
#define xtlL  (xtl||xtL)
#define xtdD  (xtd||xtD)
#define xtsS  (xts||xtS)
#define xtmM  (xtm||xtM)
#define xtzZ  (xtz||xtZ)
#define ytcC  (ytc||ytC)
#define ytbB  (ytb||ytB)
#define ythH  (yth||ytH)
#define ytiI  (yti||ytI)
#define ytlL  (ytl||ytL)
#define ytdD  (ytd||ytD)
#define ytsS  (yts||ytS)
#define ytmM  (ytm||ytM)
#define ytzZ  (ytz||ytZ)
#define ztcC  (ztc||ztC)
#define ztbB  (ztb||ztB)
#define zthH  (zth||ztH)
#define ztiI  (zti||ztI)
#define ztlL  (ztl||ztL)
#define ztdD  (ztd||ztD)
#define ztsS  (zts||ztS)
#define ztmM  (ztm||ztM)
#define ztzZ  (ztz||ztZ)
#define utcC  (utc||utC)
#define utbB  (utb||utB)
#define uthH  (uth||utH)
#define utiI  (uti||utI)
#define utlL  (utl||utL)
#define utdD  (utd||utD)
#define utsS  (uts||utS)
#define utmM  (utm||utM)
#define utzZ  (utz||utZ)
#define xtmt  (xtm||xtt)
#define ytmt  (ytm||ytt)
#define ztmt  (ztm||ztt)
#define utmt  (utm||utt)
#define xtMT  (xtM||xtT)
#define ytMT  (ytM||ytT)
#define ztMT  (ztM||ztT)
#define utMT  (utM||utT)
#define xtZD  (xtZ||xtD)
#define ytZD  (ytZ||ytD)
#define ztZD  (ztZ||ztD)
#define utZD  (utZ||utD)
#define xtzd  (xtz||xtd)
#define ytzd  (ytz||ytd)
#define ztzd  (ztz||ztd)
#define utzd  (utz||utd)
#define xtCZ  (xtC||xtZ)
#define ytCZ  (ytC||ytZ)
#define ztCZ  (ztC||ztZ)
#define utCZ  (utC||utZ)
#define xtcz  (xtc||xtz)
#define ytcz  (ytc||ytz)
#define ztcz  (ztc||ztz)
#define utcz  (utc||utz)
#define xtmMA (xtmM||xtA)
#define ytmMA (ytmM||ytA)
#define ztmMA (ztmM||ztA)
#define utmMA (utmM||utA)
#define x2(a...) _2(x,a)
#define y2(a...) _2(y,a)
#define z2(a...) _2(z,a)
#define u2(a...) _2(u,a)
#define xq(a) _q(x,a)
#define yq(a) _q(y,a)
#define zq(a) _q(z,a)
#define uq(a) _q(u,a)
#define Nx(r) N1(x,r)
#define Ny(r) N1(y,r)
#define Nz(r) N1(z,r)
#define Nu(r) N1(u,r)
#define oA    mR(ce[tA])
#define oC    mR(ce[tC])
#define oL    mR(ce[tL])
#define oD    mR(ce[tD])
#define oS    mR(ce[tS])
#define Ec(a...) E_(c,a)
#define Ed(a...) E_(d,a)
#define Ei(a...) E_(i,a)
#define El(a...) E_(l,a)
#define En(a...) E_(n,a)
#define Eo(a...) E_(o,a)
#define Ep(a...) E_(p,a)
#define Er(a...) E_(r,a)
#define Es(a...) E_(s,a)
#define Et(a...) E_(t,a)
#define Ev(a...) E_(v,a)
#define Ez(a...) E_(z,a)
#define XA(a...) P(xtA,a)
#define YA(a...) P(ytA,a)
#define XC(a...) P(xtC,a)
#define YC(a...) P(ytC,a)
#define XB(a...) P(xtB,a)
#define YB(a...) P(ytB,a)
#define XH(a...) P(xtH,a)
#define YH(a...) P(ytH,a)
#define XI(a...) P(xtI,a)
#define YI(a...) P(ytI,a)
#define XL(a...) P(xtL,a)
#define YL(a...) P(ytL,a)
#define XD(a...) P(xtD,a)
#define YD(a...) P(ytD,a)
#define XS(a...) P(xtS,a)
#define YS(a...) P(ytS,a)
#define XM(a...) P(xtM,a)
#define YM(a...) P(ytM,a)
#define Xm(a...) P(xtm,a)
#define Ym(a...) P(ytm,a)
#define Xc(a...) P(xtc,a)
#define Yc(a...) P(ytc,a)
#define Xi(a...) P(xti,a)
#define Yi(a...) P(yti,a)
#define Xl(a...) P(xtl,a)
#define Yl(a...) P(ytl,a)
#define Xd(a...) P(xtd,a)
#define Yd(a...) P(ytd,a)
#define Xs(a...) P(xts,a)
#define Ys(a...) P(yts,a)
#define Xo(a...) P(xto,a)
#define Yo(a...) P(yto,a)
#define Xp(a...) P(xtp,a)
#define Yp(a...) P(ytp,a)
#define Xq(a...) P(xtq,a)
#define Yq(a...) P(ytq,a)
#define Xr(a...) P(xtr,a)
#define Yr(a...) P(ytr,a)
#define Xu(a...) P(xtu,a)
#define Yu(a...) P(ytu,a)
#define Xv(a...) P(xtv,a)
#define Yv(a...) P(ytv,a)
#define Xw(a...) P(xtw,a)
#define Yw(a...) P(ytw,a)
#define Xe(a...) P(xte,a)
#define Ye(a...) P(yte,a)
#define XF(a...) P(xtF,a)
#define YF(a...) P(ytF,a)
#define XP(a...) P(xtP,a)
#define YP(a...) P(ytP,a)
#define XR(a...) P(xtR,a)
#define YR(a...) P(ytR,a)
#define Xz(a...) P(xtz,a)
#define Yz(a...) P(ytz,a)
#define XZ(a...) P(xtZ,a)
#define YZ(a...) P(ytZ,a)
#define Xt(a...) P(xtt,a)
#define Yt(a...) P(ytt,a)
#define XT(a...) P(xtT,a)
#define YT(a...) P(ytT,a)
#define XcC(a...) P(xtcC,a)
#define YcC(a...) P(ytcC,a)
#define XiI(a...) P(xtiI,a)
#define YiI(a...) P(ytiI,a)
#define XlL(a...) P(xtlL,a)
#define YlL(a...) P(ytlL,a)
#define XdD(a...) P(xtdD,a)
#define YdD(a...) P(ytdD,a)
#define XsS(a...) P(xtsS,a)
#define YsS(a...) P(ytsS,a)
#define XzZ(a...) P(xtzZ,a)
#define YzZ(a...) P(ytzZ,a)
#define Xmt(a...) P(xtmt,a)
#define Ymt(a...) P(ytmt,a)
#define XMT(a...) P(xtMT,a)
#define YMT(a...) P(ytMT,a)
#define XmMA(a...) P(xtmMA,a)
#define YmMA(a...) P(ytmMA,a)
#define XZD(a...) P(xtZD,a)
#define YZD(a...) P(ytZD,a)
#define Xzd(a...) P(xtzd,a)
#define Yzd(a...) P(ytzd,a)
#define XCZ(a...) P(xtCZ,a)
#define YCZ(a...) P(ytCZ,a)
#define Xcz(a...) P(xtcz,a)
#define Ycz(a...) P(ytcz,a)
#define Cb C b
#define Cc C c
#define Cd C d
#define Ck C k
#define Cn C n
#define Co C o
#define Ct C t
#define Cv C v
#define Bi B i
#define Bj B j
#define Bk B k
#define Bm B m
#define Bn B n
#define Bv B v
#define Hi H i
#define Hj H j
#define Hk H k
#define Hm H m
#define Hn H n
#define Hv H v
#define Ii I i
#define Ij I j
#define Ik I k
#define Im I m
#define In I n
#define Iv I v
#define Li L i
#define Lj L j
#define Lk L k
#define Lm L m
#define Ln L n
#define Lv L v
#define If I f
#define Dd D d
#define Dv D v
#define Ax A x
#define Ay A y
#define Az A z
#define Au A u
#define Ni N i
#define Nj N j
#define Nm N m
#define Nn N n
#define OA O A
#define OC O C
#define OV O V
#define Qs Q s
#define Qp Q p
#define Qq Q q
