#include"a.h" // ngn/k, (c) 2019-2021 ngn, GNU AGPLv3 - https://codeberg.org/ngn/k/blob/master/LICENSE
SN A flt(Ax,Ay,Cb)_(Q(xtF);P(xK-1,er2(x,y))Ym(K("{y@&z~:/x y}",x,y,ai(!b)))x=Ny(ap1(x,yR));x=xN?Ny(cL(x)):x(oL);
 P(!xtt&&xN-yN,el2(x,y))Az=rshN(0,yR);i(yN,Ln=gl(get(x,i));B(b&&n-(UI)n,z=ed1(z))j(b?n:!n,zq(get(y,i))))x(y(z)))
S V rshV(OV*a,Nm,V*b,Nn){Q(m);Mc(b,a,min(m,n));W(2*m<=n,Mc(b+m,b,m);m*=2)I(n>m,Mc(b+m,b,n-m))}
ALA(rshN,Xm(Ay=kv(&x);x=Ny(rshN(n,x));y=Nx(rshN(n,y));am(x,y))XM(Ay=kv(&x);aM(x,Nx(ear(RSH,az(n),y))))
 Xt(rshN(n,enl(x)))P(!xn,rshN(n,enl(fir(x))))P(n<0,n-NL?rev(rshN(-n,rev(x))):x)
 Ay=atn(xt,n);rshV(xV,xn*xW,yV,n*xW);x(ytA?sqz(mRa(y)):y))
S A slc(Ax/*0*/,Li,Lj)_(Q(xtT&&0<=i&&i<=j&&i<=xn)Ay=atn(xt,j-i);Mc(yV,xV+i*xW,(j-i)*xW);XA(sqz(mRa(y)))y)
S ALA(chp,Q(n>0);Lm=(xn+n-1)/n;Ay=aA(m);i(m,ya=slc(x,n*i,min(xn,n*i+n)))x(y))
S A shp(O L*s,Ln,Ax,Lm)_(P(n<=0,en1(x))m*=*s;P(n==1,rshN(m,x))chp(s[1],shp(s+1,n-1,x,m)))
A2(rsh,XF(flt(x,y,1))Xz(rshN(gl(x),y))Xm(et2(x,y))Ym(Xmt(rsh(enl(x),y))am(x,ap1(y,xR)))Yt(rsh(x,enl(y)))
 x=Ny(cL(x));Nn=xN;P(!n,fir(x(y)))P(n>8,ez2(x,y))P(n==1&&*xL==NL,x(y))P(!yn,rsh(x,enl(fir(y))))Lm=1;
 i(n,Lv=xl;m*=v;I(v<0,Ed(n>2||n==2&&v-NL,x,y)
  P(n==2,Ed(*xL<=0&&xL[1]<=0||!yn,x,y)*xL==NL?x(chp(xL[1],y)):K("{x@:0;((-x)!(#y)*!x)_y}",x,y))))
 x(m?shp(xV,n,y,1):rshN(0,enl(y))))
ALA(drp,XT(n*=n!=NL;P(n<=0&&-n<=xn&&xr==1,I(xtA,mrn(-n,xA+xn+n))AN(xn+n,x))x(slc(x,max(0,min((L)xn,n)),max(0,min((L)xn,xn+n)))))
 Xm(Ay=kv(&x);am(Ny(drp(n,x)),Nx(drp(n,y))))XM(Ay=kv(&x);aM(x,Nx(eac2(az(n),y,CUT))))er1(x))
S AAL(rmv,XT(P(!in(i,xn),x)Ay=atn(xt,xn-1);Mc(yV,xV,i*xW);Mc(yV+i*xW,xV+i*xW+xW,(xn-i-1)*xW);I(xtA,y=sqz(mRa(y)))x(y))et1(x))
A2(cut,Xz(drp(gl(x),y))XF(flt(x,y,0))Xm(Az=kv(&x);y=fnd(xR,y);P(!y,x(z(0)))yR;am(Nz(cut(x,y)),Nx(cut(z,y))))
 YMT(K("{y$[|/0<':x,#y;`err\"dom\";x+!'1_-':x,#y]}",Ny(cL(x)),y))Ym(K("{((!y)^x)#y}",x,y))Yz(rmv(x,gl(y)))et2(x,y))
A1(enl,Xi(Iv=xv;aV(v==(B)v?tB:v==(H)v?tH:tI,1,&v))Xl(Lv=*xL;v==(I)v?enl(x(ai(v))):AT(tL,mut(x)))Xd(AT(tD,mut(x)))
 P(xtzc||xts,aV(TT[xt],1,&x))Xm(Ay=kv(&x);aM(x,eac1(y,enl)))a1(x))
A1(enla,Xmt(enl(x))x)
A2(cat,
 P(xtmM&&ytmM,P(xtm&&ytm,Az=kv(&y);amd(A(x,y,av,z),4))Ed(!mtc_(xx,yx),x,y)
              Az=eac2(_R(xy),_R(yy),CAT);x(y(z?aM(_R(xx),z):0)))
 x=enla(x);P(ytT&&!yn,y(x))P(!xn,x(enla(y)))y=enla(y);I(xtZ&&ytzZ,N(sup(&x,&y)))I(xt-yt,x=blw(x);y=blw(y))
 Nm=xn,n=yn;x=room(m+n,x);Mc(xV+m*xW,yV,n*xW);y(!ytA?0:yr-1?mRa(y):AN(0,y));x)
A2(apd,XM(P(!ytm||!mtc_(xx,yx),apd(Ny(blw(x)),y))x=mut(x);Az=xy=mut(xy);i(zn,_q(za,get(yy,i)))y(x))
 Q(xtT);P(xtZ&&ytz,N(sup(&x,&y));ytP?apv(x,&y):y(apv(x,yV)))
 P(!xtA&&(!ytt||xt-TT[yt]),cat(x,enl(y)))P(!xn,enl(x(y)))Lv=xtA?(L)y:gl(y);apv(x,&v))
A apv(Ax,OV*v )_(Q(xtT);Nn=xn;x=room(n+1,x);Mc(xV+n*xW,v,xW);x)
A apc(Ax,Cc   )_(Q(xtC);Nn=xn;x=room(n+1,x);xC[n]=c;x)
A cts(Ax,Qs,Nm)_(Q(xtC);Nn=xn;x=room(n+m,x);Mc(xV+n,s,m);x)
S V mRn(Nn,OA*a){i(n,_R(a[i]))}
S A insL(Ax,Li,Ln,Ay)_(Xmt(et2(x,y))Ymt(insL(x,i,n,enl(y)))P(xtM||ytM,en2(x,y))
 P(xtZ&&ytZ&&xt-yt,V(f,cT[max(xt,yt)])insL(f(x),i,n,f(y)))P(xt-yt,insL(blw(x),i,n,blw(y)))
 P(!in(i,xN+1)||!in(n,xN+1-i),el2(x,y))
 Az=atn(xt,xn-n+yn);Mc(zV,xV,i*xW);Mc(zV+i*xW,yV,yn*xW);Mc(zV+(i+yn)*xW,xV+(i+n)*xW,(xn-n-i)*xW);
 I(xtR,I(xr-1,mRn(i,xA);mRn(xn-i-n,xA+i+n))E(mrn(n,xA+i);AN(0,x))I(yr-1,mRa(y))E(AN(0,y)))x(y(z)))
S A3(ins3,Yz(insL(x,gl(y),0,z))YZ(P(yN-2,z(el2(x,y)))Ln=gl(get(y,1));insL(x,gl(fir(y)),n,z))z(et2(x,y)))
AA(ins,P(n-3,enn(a,n))ins3(*a,a[1],a[2]))
