#include"k.h" // ngn/k, (c) 2019 ngn, GNU AGPLv3 - http://bitbucket.org/ngn/k/raw/master/LICENSE
S I lt(UC c)_(c|=32;C3('a',c,'z')||c>127)S I dg(C c)_(C3('0',c,'9'))S I ld(C c)_(lt(c)||dg(c))S I cy(UC c)_((c|1)==0xd1)
S C*s,*s0,na;S A pb(A,C);S I unh(C c)_((c&15)+9*(c>'9'))S I nu(C*s)_(dg(s[*s=='-']))S A1(p1,xn-1?x:fir(x))S I fc(O C*s,C c)_(O C*t=s;W(*t&&*t-c,t++)t-s)
S A1(v1,P(xtv&&x-cv0,cu(Av(x)))$(xtX&&xn==2&&xx==cw(0),x=mut(x);xy=v1(xy))x)L pu(C**p)_(C*s=*p;L v=0;C c=*s;W(dg(c),v=10*v+c-'0';c=*++s)*p=s;v)
S A0(pC,asrt(*s=='"');A x=aC(0);C c=*++s;W(c&&c!='"',$(c=='\\',c=*++s;I i=fc("tnr0",c);$(i<4,c="\t\n\r"[i]))x=apc(x,c);c=*++s)P(!c,ep())c=*++s;x)
A pS(C**p)_(C*s=*p,c=*s;$(c&0x80,$(cy(c),s+=2;c=*s;W(1,$(dg(c),c=*++s)E$(cy(c),s+=2;c=*s)E(B)))E(W(((c=*++s)&0xc0)==0x80)))
 E$(c==':',W(ld(c=*++s)||fc("./:",c)<3))E(W(ld(c),c=*++s))A u=aCm(*p,s);*p=s;u)
S A pSs(C d)_(A x=aS(0);W(1,L v=sym(d-'`'||*s-'"'?pS(&s):pC());x=apv(x,&v);P(*s-d,x)++s)0)L pl(C**p)_(I m=**p=='-';*p+=m;(1-2*m)*pu(p))
S A1(shy,P(!xn,x)A y=xa[xn-1];$(ytX&&yn,A z=yx;P(z==cv0||ztu&&yn>2,apd(x,cu0)))x)S A lam(C k,A s,A b,A l)_(AK(k,atnv(tX,5,A_(s,b,l,cu0,cu0))))
S A pt(C*v)_(A x;C c=*s;P(c=='"',p1(N(pC())))P(c=='`',++s;x=pSs(c);xn>1?enl(x):x)P(c=='(',s++;x=N(pb(enl(cv_mkl),')'));xn-2?x:xy==cv_plc?xr,a0():las(x))
 P(lt(c),C*t=s;x=pSs('.');$(s-t==1&&(c=='y'||c=='z'),na=max(na,c-'w'))AO(t-s0,p1(x)))
 P(c=='{',C*s1=s0,*t=s0=s++;A y;$(*s-'[',y=cu0)E(s++;y=sqz(N(pb(a0(),']')));P(!ytS||yn>8,ep(y)))
  C nb=na;na=1;A z=pb(a0(),'}');P(!z,yr;s0=s1;0)$(y==cu0,y=atnv(tS,na,(L[]){1,2,3}))E(na=yn)x=cpl(lam(na,aCn(t,s-t),shy(z),y));s0=s1;na=nb;x)
 I i=fc("'/\\[",c);P(i<3,c=*++s;P(i==2&&(!c||c=='\\'||lt(c)),C*t=s;W(c&&c-10,c=*++s)AO(t-s0,a2(cu_cmd,aCm(t,s))))I h=c==':';s+=h;*v=1;cw(i+3*h))
 P(nu(s)&&(c-'-'||({C b=s[-1];!ld(b)&&fc(")]}\"",b)==4;})),P(s[1]==':',L u=s[2]==':';s+=2+u;L i=20+c-'0';*v=1;u?cu(i):cv(i))
  P(c=='0'&&s[1]=='x',s+=2;C*p=s;W(dg(*p)||C3('a',*p,'f'),p++)L m=(p-s)/2;x=aC(m);F(m,xci=unh(*s)<<4|unh(s[1]);s+=2)p1(x))
  L fp=0;C*p=s;c=*p;W(1,p+=*p==32;p+=*p=='-';c=*p;$(!ld(c),B)W(ld(c)||c=='.'||c==':',fp|=c=='.'||c=='n'||c=='w';c=*++p))
  P(!fp,x=aL(0);W(1,L l=pl(&s);c=*s;$(!l,$(c=='W',l=s[-2]=='-'?-_0W:_0W;c=*++s)E$(c=='N',l=_0N;c=*++s))x=apd(x,al(l));$(c-32||!nu(s+1),B)c=*++s)p1(x))
  x=aD(0);W(1,L m=*s=='-';s+=m;D d=0;c=*s;W(dg(c),d=10*d-'0'+c;c=*++s)
              $(c=='.',c=*++s;D w=.1;W(dg(c),d+=w*(c-'0');c=*++s;w/=10))E$(c=='n',c=*++s,d=_0n)E$(c=='w',c=*++s;d=_0w)
              d*=1-2*m;x=apd(x,ad(d));$(c-32||!nu(s+1),B)c=*++s)p1(x))
 i=fc(vc,c);P(i>19,cv_plc)I u=*++s==':';s+=u;*v=1;u?cu(i):cv(i))
S A pT(C*v)_(A x=pt(v);W(1,C c=*s;I i=fc("'/\\[",c);$(i==3,UH o=s-s0;s++;x=AO(o,N(pb(a1(x),']')));$(xn==2&&xy==cv_plc,xy=cu0)*v=0)
                                                    E(P(i>2,x)I u=*++s==':';s+=u;x=a2(cw(i+3*u),x);*v=1))x)
S V pw()_(C c=*s;W(c==32,c=*++s)P(c-'/')c=s[-1];P(s>s0&&c-32&&c-10)W((c=*++s)&&c-10))
S A pe(A x,C*v)_(pw();UH o=s-s0;C w=0;A y=pT(&w);P(!y,$(x,xr)0)P(y==cv_plc,x?x:y)P(!w,A z=pe(y,v);P(!x,z)Nx(z);*v?a3(cv_com,x,z):AO(o,a2(x,z)))
 A z=pe(0,v);P(!z,$(x,xr)yr;0)P(z==cv_plc,*v=1;x?AO(o,a3(y,x,z)):y)
 *v&=y!=cv0;$(!x,y=v1(y))*v?a3(cv_com,x?AO(o,a3(y,x,cv_plc)):y,z):AO(o,x?a3(y,x,z):a2(y,z)))
S A pb(A x,C e)_(W(1,C v=0;A y=Nx(pe(0,&v));$(y==cv_plc&&(!e||e=='}'),y=cu0)x=apv(x,&y);$(*s-';'&&*s-10,B)s++)P(*s-e,ep(x))s++;x)
A1(prs,P(!xtC,et(x))s=s0=C(x=str0(x));A y=pb(a0(),0);!y?eso(x,s-s0),0:lam(0,x,shy(y),aS(0)))
