#!../k
/https://codegolf.stackexchange.com/questions/52946/backhandedhhhhhhspaces/223161#223161
f:{x_/3#-1+x?"^"}/

\l 0.k
t["Horse^H^H^H^H^HCow";"Cow"]
t["Be nice to this fool^H^H^H^Hgentleman, he's visiting from corporate HQ.";"Be nice to this gentleman, he's visiting from corporate HQ."]
t["123^H45^H^H^H78^H";"17"]
t["Digital Trauma^H^H^H^H^H^H^H^H^H^H^H^H^H^HMaria Tidal Tug^H^H^H^H^H^H^H^H^H^H^H^H^H^H^HDigital Trauma";"Digital Trauma"]
