#!../k
/https://codegolf.stackexchange.com/questions/217077/bedevil-your-hangman-opponent/217086#217086
f:{x@*>+//'+x=/:&c=&/c:#'=,/x}

\l 0.k
t[("one";"wont";"tee");"wont"]
t[("aaa";"bbb";"ccc");"aaa"]
t[(,"oneword");"oneword"]
t[("thee";"lee");"thee"]
t[("tee";"lee");"tee"]
t[("three";"eon";"one";"holt");"three"]
t[("xeon";"threes";"eon";"one";"holt");"threes"]
t[("xeon";"threes";"eon";"one";"holt";"apple";"mango";"george";"any";"fine");"fine"]
