/https://codegolf.stackexchange.com/questions/203893/bl-lu-ur-rr-ry-yv-vi-is-si-io-on-blur-the-input/203899#203899
f:" "/2'(2!+/"/9@Z`z"<)#
\l 0.k
t["Ab";"Ab"]
t["Abc";"Ab bc"]
t["Abcd";"Ab bc cd"]
t["Eh?";"Eh"]
t["Blurry vision";"Bl lu ur rr ry yv vi is si io on"]
t["I'm an example!";"Im ma an ne ex xa am mp pl le"]
t["This is _not_ legible";"Th hi is si is sn no ot tl le eg gi ib bl le"]
t["(a*b*c)+5^-x";"ab bc c5 5x"]
