/https://codegolf.stackexchange.com/questions/61903/code-the-huffman/178621#178621
f:{h::0#'x;(#1_){{h[x],:!2;y,,,/x}.0 2_x@<#'x}/.=x;(?,/'x,'" ",'|'$h)(?x)?>#'=x}
\l 0.k
t["this question is about huffman coding"
  ("  100"
   "i 001"
   "t 1011"
   "s 1100"
   "u 1101"
   "o 1110"
   "n 1111"
   "h 0001"
   "a 0100"
   "f 0101"
   "q 01100"
   "e 01101"
   "b 01110"
   "m 01111"
   "c 10100"
   "d 10101"
   "g 0000")]
