#!../k
/https://codegolf.stackexchange.com/questions/214077/implement-smokeys-alive-command/214096#214096
f:{*1?";"\"Yup;You doubt me?;Of course;... did I miss something?;plz send teh coffee;Watching this endless list of new questions never gets boring;Kinda sorta;You should totally drop that and use jQuery;¯\\_(ツ)_/¯;... good question"}

\l 0.k
t[::;"Yup"]
t[::;"... did I miss something?"]
t[::; "Of course"]
t[::;"Watching this endless list of new questions never gets boring"]
