/https://codegolf.stackexchange.com/questions/183544/marquee-sign-letters/184760#184760
f:*+(){(a;x,a:&0|-/#''='(y;x@:1))}\
\l 0.k
t[("ONE";"TWO";"THREE";"SEVENTEEN")
  ("ONE";"TW";"HRE";"SEEVN")]
t[("ONE";"TWO";"ONE";"THREE")
  ("ONE";"TW";"";"HRE")]
t[("ABC";"AABC";"ABBC";"ABCC";"AABBCC")
  ("ABC";,"A";,"B";,"C";"")]
t[("SHORT";"LOONG";"LOOOONG";"LOOOOOOONG";"SHORT";"LOOONG")
  ("SHORT";"LONG";"OO";"OOO";"";"")]
