#!/../k
/ https://codegolf.stackexchange.com/questions/163141/ot-wes-thi-bist-uf-tomis
f:{y^'x[<x]x?y}"UAEIOuaeio"

\l 0.k
t[,/("It was the best of times, it was the worst of times,"
     "it was the age of wisdom, it was the age of foolishness,"
     "it was the epoch of belief, it was the epoch of incredulity,"
     "it was the season of light, it was the season of darkness,"
     "it was the spring of hope, it was the winter of despair,"
     "we had everything before us, we had nothing before us,"
     "we were all going direct to heaven, we were all going direct the other way –"
     "in short, the period was so far like the present period,"
     "that some of its noisiest authorities insisted on its being received,"
     "for good or for evil, in the superlative degree of comparison only.")
  ,/("Ot wes thi bist uf tomis, ot wes thi wurst uf tomis,"
     "ot wes thi egi uf wosdum, ot wes thi egi uf fuuloshniss,"
     "ot wes thi ipuch uf biloif, ot wes thi ipuch uf oncridaloty,"
     "ot wes thi siesun uf loght, ot wes thi siesun uf derkniss,"
     "ot wes thi sprong uf hupi, ot wes thi wontir uf dispeor,"
     "wi hed ivirythong bifuri as, wi hed nuthong bifuri as,"
     "wi wiri ell guong dorict tu hievin, wi wiri ell guong dorict thi uthir wey –"
     "on shurt, thi piroud wes su fer loki thi prisint piroud,"
     "thet sumi uf ots nuosoist eathurotois onsostid un ots biong riciovid,"
     "fur guud ur fur ivol, on thi sapirletovi digrii uf cumperosun unly.")]
t["The quick brown fox jumps over the lazy dog."
  "Thi qaock bruwn fux jamps uvir thi lezy dug."]
t["Home is where the heart is."
  "Humi os whiri thi hiert os."]
t["Boaty McBoatface"
  "Buety McBuetfeci"]
t["AEIOUaeiou"
  "EIOUAeioua"]
t["Programming Puzzles And Code Golf"
  "Prugremmong Pazzlis End Cudi Gulf"]
