#!../k
/https://codegolf.stackexchange.com/questions/195022/whos-who-in-the-name-change-game/226365#226365
f:{(>x)!x@>x}((0#`)!0){(n;a):y;$[`i~@a;@[x;n;+;a];n_@[x;a;:;0^x@n]]}/

\l 0.k
t[((`Alice;5); (`Bob;7); (`Bob;`John); (`John;113); (`Alice;`Cheryl); (`Daniel;13); (`John;`Alice); (`Alice;12));`Alice`Daniel`Cheryl!132 13 5]
t[((`Jimmy;`Adam);(`Donald;12);(`Amelia;-11));`Donald`Adam`Amelia!12 0 -11]
t[((`CodegoLfer65;12);(`Bluman;9);(`CodegoLfer65;`n4me);(`n4me;-3));`Bluman`n4me!9 9]
